#!/bin/bash

PREFIX=$(base64 < /dev/urandom | tr -dc '[:lower:]' | fold -w 8 | head -n 1)
REGION="ap-northeast-1"
STACK_NAME="${PREFIX}-apigw-mock"

aws cloudformation deploy \
  --template-file ./template.yaml \
  --stack-name "${STACK_NAME}" \
  --parameter-overrides Prefix="${PREFIX}" \
  --region ${REGION}
